### PR TITLE
validate credential issuer

### PR DESCRIPTION
**Pull request by kezike**
This PR verifies that the issuer is a member of the DCC

### CODE REVIEW

**Comment by kezike** [comment]
This PR is failing because the issuer on the test credentials is not currently included in the [DCC issuer registry](https://digitalcredentials.github.io/issuer-registry/registry.json). [Here is a PR](https://github.com/digitalcredentials/issuer-registry/pull/2) to fix this.

**Comment by kezike** [comment]
Just recently rediscovered this PR and fixed some broken tests. Two important notes about this PR:
- This feature was originally implemented in [this PR to Digital Bazaar's `vc-js` library](https://github.com/digitalbazaar/vc-js/pull/105). However, we agreed that issuer validation was too use-case-specific for a core VC library, so I moved it here instead. On second thought, I am wondering if we should place this validation in the higher level `sign-and-verify` service as opposed to here in `sign-and-verify-core`?
- Currently, the validation status is merged in the same property (`verified`) as the verification check (see [here](https://github.com/digitalcredentials/sign-and-verify-core/pull/8/files#diff-0f2af736394bc2d905c16e30f1e7fd86b242b64bf4a95485b40e9f75d0a33730R67)). I was thinking of potentially moving it to its own `valid` property, but that would just mean that `sign-and-verify` instances would need to know to read this new property. Is this separation of concerns worth the extra documentation and behavior education?

**Comment by dmitrizagidulin** [comment]
@kezike 
>  On second thought, I am wondering if we should place this validation in the higher level sign-and-verify service as opposed to here in sign-and-verify-core?

Yeah, I think it'd be better to move it to `sign-and-verify` (and pass in the issuer registry into the call to core).

**Review by dmitrizagidulin — APPROVED** [review]
👍

**Pull request merged**
